---
global:
  gc: {{.GC}}
  indexerConfig:
    esServers: ["{{.ES_SERVER}}"]
    insecureSkipVerify: true
    defaultIndex: {{.ES_INDEX}}
    type: {{.INDEXING_TYPE}}
  measurements:
    - name: podLatency
      thresholds:
        - conditionType: Ready
          metric: P99
          threshold: {{.POD_READY_THRESHOLD}}
jobs:
  - name: node-density-heavy
    namespace: node-density-heavy
    jobIterations: {{.JOB_ITERATIONS}}
    qps: {{.QPS}}
    burst: {{.BURST}}
    namespacedIterations: {{.NAMESPACED_ITERATIONS}}
    iterationsPerNamespace: {{.ITERATIONS_PER_NAMESPACE}}
    podWait: false
    waitWhenFinished: true
    preLoadImages: true
    preLoadPeriod: 15s
    namespaceLabels:
      security.openshift.io/scc.podSecurityLabelSync: false
      pod-security.kubernetes.io/enforce: privileged
      pod-security.kubernetes.io/audit: privileged
      pod-security.kubernetes.io/warn: privileged
    objects:

      - objectTemplate: postgres-deployment.yml
        replicas: 1

      - objectTemplate: app-deployment.yml
        replicas: 1
        inputVars:
          probesPeriod: {{.PROBES_PERIOD}}

      - objectTemplate: postgres-service.yml
        replicas: 1
