kind: Deployment
apiVersion: apps/v1
metadata:
  name: postgres-{{.Replica}}-{{.Iteration}}
spec:
  template:
    metadata:
      labels:
        name: postgres-{{.Replica}}-{{.Iteration}}
        app: postgres
    spec:
      topologySpreadConstraints:
      - maxSkew: 1 
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway 
        labelSelector: 
          matchLabels:
            app: postgres
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: Exists
              - key: node-role.kubernetes.io/infra
                operator: DoesNotExist
              - key: node-role.kubernetes.io/workload
                operator: DoesNotExist
      containers:
      - name: postgresql
        image: registry.redhat.io/rhel8/postgresql-10@sha256:4b912c80085b88a03309aeb7907efcc29dd3342fa3952b6ea067afb1914bfe53
        ports:
        - containerPort: 5432
          protocol: TCP
        env:
        - name: POSTGRESQL_USER
          value: admin
        - name: POSTGRESQL_PASSWORD
          value: secret
        - name: POSTGRESQL_DATABASE
          value: node-density
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: false
        resources:
          requests:
            memory: "20Mi"
            cpu: "20m"
      restartPolicy: Always
  replicas: 1
  selector:
    matchLabels:
      name: postgres-{{.Replica}}-{{.Iteration}}
  strategy:
    type: RollingUpdate
