kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: pvc-density-{{.Iteration}}
  name: pvc-{{.Iteration}}
spec:
  accessModes:
  -  ReadWriteOnce
  resources:
    requests:
      storage: {{.claimSize}}