apiVersion: k8s.ovn.org/v1
kind: AdminPolicyBasedExternalRoute
metadata:
  name: honeypotting-{{ .Iteration }}-{{.JobName }}
spec:
## gateway example
  from:
    namespaceSelector:
      matchLabels:
          kubernetes.io/metadata.name: served-ns-{{ .Iteration }}
  nextHops:
    # static:
    #   - ip: "192.168.{{ add 218 .Replica }}.{{ add 1 .Iteration }}"
    #     bfdEnabled: true
    dynamic:
      - podSelector:
          matchLabels:
            lb: lb-{{ .Iteration }}
        bfdEnabled: true
        namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: serving-ns-{{ .Iteration }}
        networkAttachmentName: serving-ns-{{ .Iteration }}/sriov-net-{{ .Iteration }}