apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: get-routes-to-sa-{{ .Iteration }}
subjects:
  - kind: ServiceAccount
    name: internal-kubectl
    namespace: serving-ns-{{ .Iteration }}
roleRef:
  kind: ClusterRole
  name: get-routes
  apiGroup: rbac.authorization.k8s.io

