---
kind: Deployment
apiVersion: apps/v1
metadata:    
  name: dep-served-init-{{ .Iteration }}-{{ .Replica }}-{{.JobName }}
spec:
  template:
    metadata:
      name: pod-served-{{ .Iteration }}-{{ .Replica }}-{{.JobName }}
      labels:
        app: served-init-{{ .Iteration }}-{{ .Replica }}-{{.JobName }}
    spec:
      containers:
      - args:
        - sleep
        - infinity
        name: app
        image: quay.io/centos/centos
        ports:
        - containerPort: 80
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/worker-spk
                operator: DoesNotExist
  replicas: 1
  selector:
    matchLabels:
     app: served-init-{{ .Iteration }}-{{ .Replica }}-{{.JobName }}
  strategy:
    type: RollingUpdate 
