---
global:
  gc: {{.GC}}
  gcMetrics: {{.GC_METRICS}}
  indexerConfig:
    esServers: ["{{.ES_SERVER}}"]
    insecureSkipVerify: true
    defaultIndex: {{.ES_INDEX}}
    type: {{.INDEXING_TYPE}}
  measurements:
    - name: podLatency
      thresholds:
        - conditionType: Ready
          metric: P99
          threshold: {{.POD_READY_THRESHOLD}}

jobs:

  - name: create-networks-job
    jobType: create
    jobIterations: {{ mul .LIMITCOUNT .SCALE }}
    qps: 10
    burst: 10
    namespacedIterations: {{ if contains .SRIOV "true" }} false {{ else }} true {{ end }}
    cleanup: false
    namespace: {{ if contains .SRIOV "true" }} openshift-sriov-network-operator {{ else }} serving-ns {{ end }}
    podWait: false
    waitWhenFinished: false
    verifyObjects: true
    errorOnVerify: false
    jobIterationDelay: 1s
    jobPause: 0s
    preLoadImages: false
    objects:
      - objectTemplate: {{ if contains .SRIOV "true" }} sriov_network.yml {{ else }} macvlan_network.yml {{ end }}
        replicas: 1
        inputVars:
          bridge: {{ .BRIDGE }}

  - name: create-serviceaccounts-job
    jobType: create
    jobIterations: {{ mul .LIMITCOUNT .SCALE }}
    qps: 20
    burst: 20
    namespacedIterations: true
    cleanup: false
    namespace: serving-ns
    podWait: false
    waitWhenFinished: false
    verifyObjects: true
    errorOnVerify: false
    jobIterationDelay: 1s
    jobPause: 0s
    preLoadImages: false
    objects:
      - objectTemplate: permissionsServiceAccount.yml
        replicas: 1

  - name: create-clusterrole-job
    jobType: create
    jobIterations: 1
    qps: 20
    burst: 20
    namespacedIterations: false
    cleanup: false
    namespace: default
    podWait: false
    waitWhenFinished: false
    verifyObjects: true
    errorOnVerify: false
    jobIterationDelay: 1s
    jobPause: 0s
    preLoadImages: false
    objects:
      - objectTemplate: permissionsClusterRole.yml
        replicas: 1

  - name: create-clusterbindings-jobs
    jobType: create
    jobIterations: {{ mul .LIMITCOUNT .SCALE }}
    qps: 20
    burst: 20
    namespacedIterations: true
    cleanup: false
    namespace: serving-ns
    podWait: false
    waitWhenFinished: false
    verifyObjects: true
    errorOnVerify: false
    jobIterationDelay: 1s
    jobPause: 0s
    preLoadImages: false
    objects:
      - objectTemplate: permissionsClusterRoleBinding.yml
        replicas: 1

  - name: create-rolebindings-jobs
    jobType: create
    jobIterations: {{ mul .LIMITCOUNT .SCALE }}
    qps: 20
    burst: 20
    namespacedIterations: true
    cleanup: false
    namespace: serving-ns
    podWait: false
    waitWhenFinished: false
    verifyObjects: true
    errorOnVerify: false
    jobIterationDelay: 1s
    jobPause: 0s
    preLoadImages: false
    objects:
      - objectTemplate: permissionsRoleBinding.yml
        replicas: 1

  - name: create-cms-job
    jobType: create
    jobIterations: {{ mul .LIMITCOUNT .SCALE }}
    qps: 20
    burst: 20
    namespacedIterations: true
    cleanup: false
    namespace: serving-ns
    podWait: false
    waitWhenFinished: false
    verifyObjects: true
    errorOnVerify: false
    jobIterationDelay: 1s
    jobPause: 0s
    preLoadImages: false
    objects:
      - objectTemplate: cm_frr.yml
        replicas: 1

  - name: init-served-job
    jobType: create
    jobIterations: {{ mul .LIMITCOUNT .SCALE }}
    qps: 20
    burst: 20
    namespacedIterations: true
    cleanup: false
    namespace: served-ns
    podWait: false
    waitWhenFinished: true
    verifyObjects: true
    errorOnVerify: true
    jobIterationDelay: 0s
    jobPause: 0s
    preLoadImages: false
    objects:
      - objectTemplate: pod_served.yml
        replicas: 1

{{ if contains .CRD "true" }}
  - name: init-externalroutes-job
    jobType: create
    jobIterations: {{ mul .LIMITCOUNT .SCALE }}
    qps: 20
    burst: 20
    namespacedIterations: false
    cleanup: false
    namespace: default
    podWait: false
    waitWhenFinished: true
    verifyObjects: true
    errorOnVerify: true
    jobIterationDelay: 0s
    jobPause: 0s
    preLoadImages: false
    objects:
      - objectTemplate: adminPolicyBasedExternalRoute.yml
        replicas: 1
{{ end }}

  - name: serving-job
    jobType: create
    jobIterations: {{ mul .LIMITCOUNT .SCALE }}
    qps: 20
    burst: 20
    namespacedIterations: true
    cleanup: false
    namespace: serving-ns
    podWait: false
    waitWhenFinished: true
    verifyObjects: true
    errorOnVerify: true
    jobIterationDelay: 0s
    jobPause: 0s
    preLoadImages: false
    objects:
      - objectTemplate: {{ if contains .BFD "true" }} pod_serving.yml {{ else }} pod_serving_no_bfd.yml {{ end }}
        replicas: 4
        inputVars:
          crd: "{{ $.CRD }}"
