apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: rmq-consumer-so-{{.Iteration}}
spec:
  scaleTargetRef:
    name: rmq-consumer-{{.Iteration}}
  pollingInterval: {{.pollingInterval}}
  cooldownPeriod: {{.cooldownPeriod}}
  minReplicaCount: {{.minReplicaCount}}
  maxReplicaCount: {{.maxReplicaCount}}
  triggers:
    - type: rabbitmq
      metadata:
        queueName: perf-queue-{{.Iteration}}
        queueLength: {{.queueLength}}
        hostFromEnv: RABBITMQ_URL
