{
 "title": "OpenShift CI - api & etcd",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Datasource", "query": "elasticsearch" },
   {
    "name": "uuid",
    "label": "UUID",
    "query": "{\"find\": \"terms\", \"field\": \"uuid.keyword\"}"
   },
   {
    "name": "master",
    "label": "Master nodes",
    "query": "{ \"find\" : \"terms\", \"field\": \"labels.node.keyword\", \"query\": \"metricName.keyword: nodeRoles AND labels.role.keyword: master AND uuid.keyword: $uuid\"}"
   },
   {
    "name": "job_name",
    "label": "Job Name",
    "query": "{ \"find\" : \"terms\", \"field\": \"jobConfig.name.keyword\",  \"query\": \"metricName.keyword: jobSummary AND uuid.keyword: $uuid\"}"
   },
   {
    "name": "verb",
    "label": "Verb",
    "query": "{ \"find\" : \"terms\", \"field\": \"labels.verb.keyword\",  \"query\": \"metricName.keyword: P99APICallsLatency AND uuid.keyword: $uuid\"}"
   },
   {
    "name": "resource",
    "label": "Resource",
    "query": "{ \"find\" : \"terms\", \"field\": \"labels.resource.keyword\",  \"query\": \"metricName.keyword: P99APICallsLatency AND uuid.keyword: $uuid\"}"
   },
   {
    "name": "code",
    "label": "Status code",
    "query": "{ \"find\" : \"terms\", \"field\": \"labels.code.keyword\",  \"query\": \"metricName.keyword: APIRequestRate AND uuid.keyword: $uuid\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Job Summary",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "metrics": [
      {
       "$$hashKey": "object:409",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_data"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"jobSummary\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Node status summary",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:4404",
       "fake": true,
       "field": "labels.condition.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"nodeStatus\" AND jobName.keyword: $job_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ConfigMap count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: configmapCount AND jobName.keyword: $job_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Node count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:4404",
       "fake": true,
       "field": "labels.role.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "coun",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"nodeRoles\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Etcd version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "versi",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_data"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"etcdVersion\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "OpenShift version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "versi",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_data"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"clusterVersion\"",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "P99 API calls latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "{{term labels.verb.keyword}} {{term labels.resource.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:1483",
       "fake": true,
       "field": "labels.resource.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1330",
       "fake": true,
       "field": "labels.verb.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: P99APICallsLatency AND jobName.keyword: $job_name AND labels.verb.keyword: $verb AND labels.resource.keyword: $resource",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "API request rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "alias": "{{term labels.verb.keyword}} {{term labels.resource.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:1483",
       "fake": true,
       "field": "labels.resource.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1330",
       "fake": true,
       "field": "labels.verb.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: APIRequestRate AND jobName.keyword: $job_name AND labels.verb: $verb AND labels.resource: $resource",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "API Status code rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "{{term labels.verb.keyword}} {{term labels.code.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:1850",
       "fake": true,
       "field": "labels.verb.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1330",
       "fake": true,
       "field": "labels.code.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: APIRequestRate AND jobName.keyword: $job_name AND labels.verb: $verb AND labels.code.keyword: $code",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "API Inflight requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "alias": "{{term labels.request_kind.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:1850",
       "fake": true,
       "field": "labels.request_kind.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: APIInflightRequests AND jobName.keyword: $job_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "P99 API -> etcd request latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "{{term labels.apiserver.keyword}} {{term labels.operation.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:1850",
       "fake": true,
       "field": "labels.operation.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1330",
       "fake": true,
       "field": "labels.apiserver.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: P99APIEtcdRequestLatency AND jobName.keyword: $job_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "FlowSchema request rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "alias": "{{term labels.flow_schema.keyword}} {{term labels.priority_level.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:1850",
       "fake": true,
       "field": "labels.flow_schema.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1330",
       "fake": true,
       "field": "labels.priority_level.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: flowControlRate AND jobName.keyword: $job_name",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "etcd", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "etcd 99th fsync latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:4404",
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"99thEtcdDiskWalFsyncDurationSeconds\" AND jobName.keyword: $job_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "etcd 99th disk commit latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:4404",
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:33",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:31",
       "field": "value",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"99thEtcdDiskBackendCommitDurationSeconds\" AND jobName.keyword: $job_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Etcd 99th network peer roundtrip time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "{{labels.pod.keyword}} to {{labels.To.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:806",
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:322",
       "fake": true,
       "field": "labels.To.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:259",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:278",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: 99thEtcdRoundTripTimeSeconds AND jobName.keyword: $job_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Etcd WAL write rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "alias": "{{term labels.pod.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:563",
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:280",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:278",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: etcdWALWriteBytesRate AND jobName.keyword: $job_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Etcd DB size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Physical size: {{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:322",
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:259",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:278",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: etcdDBPhysicalSizeBytes AND jobName.keyword: $job_name",
     "timeField": "timestamp"
    },
    {
     "alias": "Logical size: {{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:337",
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:280",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:278",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: etcdDBLogicalSizeBytes AND jobName.keyword: $job_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "gRPC etcd clients byte/rate",
   "type": "graph",
   "description": "etcd gRPC clients received/sent bytes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "received-{{term labels.pod.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:1170",
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:4301",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:4299",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: etcdClientGRPCReceivedBytesRate AND jobName.keyword: $job_name",
     "timeField": "timestamp"
    },
    {
     "alias": "sent-{{term labels.pod.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:1170",
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:4301",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:4299",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: etcdClientGRPCSentBytesRate AND jobName.keyword: $job_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Etcd leader",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Etcd leader changes",
     "bucketAggs": [
      {
       "$$hashKey": "object:280",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:278",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: etcdLeaderChangesRate AND jobName.keyword: $job_name",
     "timeField": "timestamp"
    },
    {
     "alias": "Current leader: {{term labels.pod.keyword}}",
     "bucketAggs": [
      {
       "$$hashKey": "object:375",
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:280",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:278",
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: etcdServerIsLeader AND jobName.keyword: $job_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Golang stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "collapsed": true,
   "panels": [
    {
     "title": "Go heap allocation",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:6239",
         "fake": true,
         "field": "labels.job.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:5868",
         "fake": true,
         "field": "labels.instance.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"goHeapAllocBytes\" AND jobName.keyword: $job_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Go heap inuse",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:6418",
         "fake": true,
         "field": "labels.job.keyword",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:6404",
         "fake": true,
         "field": "labels.instance.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"goHeapInuseBytes\" AND jobName.keyword: $job_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Go GC duration",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "$$hashKey": "object:6121",
         "fake": true,
         "field": "labels.job.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:5868",
         "fake": true,
         "field": "labels.instance.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"goGCDurationSeconds\" AND jobName.keyword: $job_name",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Master: $master",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "repeat": "master",
   "collapsed": true,
   "panels": [
    {
     "title": "Container CPU usage $master",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "{{labels.pod.keyword}} {{labels.container.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:2461",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:159",
         "fake": true,
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"containerCPU-Masters\" AND labels.node.keyword: $master AND jobName.keyword: $job_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Container RSS Memory usage $master",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "{{labels.pod.keyword}} {{labels.container.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:2461",
         "fake": true,
         "field": "labels.pod.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:159",
         "fake": true,
         "field": "labels.container.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"containerMemory-Masters\" AND labels.node.keyword: $master AND jobName.keyword: $job_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "CPU $master",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "{{labels.mode.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:133",
         "fake": true,
         "field": "labels.mode.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "inlineScript": "_value*100",
         "meta": {},
         "settings": { "script": { "inline": "_value*100" } },
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"nodeCPU-Masters\" AND labels.instance.keyword: $master AND jobName.keyword: $job_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Network bytes $master",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "txNetworkBytes - {{labels.device.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:1174",
         "fake": true,
         "field": "labels.device.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:1089",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:1087",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid: $uuid AND metricName: \"txNetworkBytes-Masters\" AND labels.instance.keyword: \"$master\" AND jobName.keyword: $job_name",
       "timeField": "timestamp"
      },
      {
       "alias": "rxNetworkBytes - {{labels.device.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:1215",
         "fake": true,
         "field": "labels.device.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:1195",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:1193",
         "field": "value",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid: $uuid AND  metricName: \"rxNetworkBytes-Masters\" AND labels.instance.keyword: \"$master\" AND jobName.keyword: $job_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Block read/write rate: $master",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Write {{labels.device.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:438",
         "fake": true,
         "field": "labels.device.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:543",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:541",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: diskWriteBytesRate AND labels.instance.keyword: $master AND jobName.keyword: $job_name",
       "timeField": "timestamp"
      },
      {
       "alias": "Read {{labels.device.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:438",
         "fake": true,
         "field": "labels.device.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:543",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:541",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: diskReadBytesRate AND labels.instance.keyword: $master AND jobName.keyword: $job_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Block read/write IOPS: $master",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "Write {{labels.device.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:438",
         "fake": true,
         "field": "labels.device.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:543",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:541",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: writeOpsSec AND labels.instance.keyword: $master AND jobName.keyword: $job_name",
       "timeField": "timestamp"
      },
      {
       "alias": "Read {{labels.device.keyword}}",
       "bucketAggs": [
        {
         "$$hashKey": "object:438",
         "fake": true,
         "field": "labels.device.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "$$hashKey": "object:543",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:541",
         "field": "value",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: readOpsSec AND labels.instance.keyword: $master AND jobName.keyword: $job_name",
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Memory $master",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 76 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "available",
       "bucketAggs": [
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"nodeMemoryAvailable-Masters\" AND labels.instance.keyword: $master AND jobName.keyword: $job_name",
       "timeField": "timestamp"
      },
      {
       "alias": "active",
       "bucketAggs": [
        {
         "$$hashKey": "object:33",
         "field": "timestamp",
         "id": "2",
         "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "$$hashKey": "object:31",
         "field": "value",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "uuid.keyword: $uuid AND metricName: \"nodeMemoryActive-Masters\" AND labels.instance.keyword: $master AND jobName.keyword: $job_name",
       "timeField": "timestamp"
      }
     ]
    }
   ]
  }
 ]
}