{
 "title": "Kube-burner CNV report",
 "time": { "from": "2022-01-15T01:30:00.000Z", "to": "2022-01-15T06:00:59.000Z" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Datasource", "query": "elasticsearch" },
   {
    "name": "uuid",
    "label": "Job UUID",
    "query": "{\"find\": \"terms\", \"field\": \"uuid.keyword\", \"query\": \"metricName.keyword: jobSummary\"}"
   },
   {
    "name": "master",
    "label": "Master nodes",
    "query": "{ \"find\" : \"terms\", \"field\": \"labels.node.keyword\", \"query\": \"metricName.keyword: nodeRoles AND labels.role.keyword: master AND uuid.keyword: $uuid\"}"
   },
   {
    "name": "worker",
    "label": "Worker nodes",
    "query": "{ \"find\" : \"terms\", \"field\": \"labels.node.keyword\", \"query\": \"metricName.keyword: nodeRoles AND labels.role.keyword: worker AND uuid.keyword: $uuid\"}"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "{ \"find\" : \"terms\", \"field\": \"labels.namespace.keyword\", \"query\": \"labels.namespace.keyword: /openshift-.*/ AND uuid.keyword: $uuid\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Node count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.role.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "coun",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"nodeRoles\"",
     "timeField": "timestamp"
    },
    {
     "alias": "ready state",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"nodeStatus\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "OpenShift version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metrics": [
      {
       "field": "versi",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_data"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"clusterVersion\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "CNV (Kubevirt) version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_data"
      }
     ],
     "query": "metricName: kubevirtVersion",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Etcd version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metrics": [
      {
       "field": "versi",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_data"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"etcdVersion\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Namespaces",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"namespaceCount\"",
     "timeField": "timestamp"
    },
    {
     "alias": "Services",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"serviceCount\"",
     "timeField": "timestamp"
    },
    {
     "alias": "Configmap",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"configmapCount\"",
     "timeField": "timestamp"
    },
    {
     "alias": "Secret",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"secretCount\"",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "CNV (Kubevirt) VM/VMI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "VMIPod/Node Count and Balance ",
   "type": "graph",
   "description": "count(container_cpu_usage_seconds_total{pod=~\".*virt-launcher.*\", container=\"compute\", node!~\".*master.*\", service=\"kubelet\"}) by (node) > 0",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.phase.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: vmiStatusCount",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VM Phase Transition Rate",
   "type": "graph",
   "description": "sum(rate(kubevirt_vmi_phase_transition_time_from_creation_seconds_count{}[5m])) by (phase) > 0",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{labels.phase.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.phase.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: vmiStatusRate",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VMIPod/Node Count and Balance ",
   "type": "graph",
   "description": "count(container_cpu_usage_seconds_total{pod=~\".*virt-launcher.*\", container=\"compute\", node!~\".*master.*\", service=\"kubelet\"}) by (node) > 0",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {
        "avg": true,
        "count": false,
        "max": true,
        "min": true,
        "std_deviation": true,
        "std_deviation_bounds_lower": false,
        "std_deviation_bounds_upper": false,
        "sum": true
       },
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: vmiNodeCount  AND NOT labels.node.keyword: master*",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VMs Creation Latency Breakdown",
   "type": "graph",
   "description": "If the VMI was created by a VM object, the VM creation time is the baseline timestamp, otherwise the VMI creation time is used as the baseline timestamp.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "VMReady",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "vmReadyLatency",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: vmiLatencyMeasurement AND vmReadyLatency > 0",
     "timeField": "timestamp"
    },
    {
     "alias": "VMIReady",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "vmiReadyLatency",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "timestamp"
    },
    {
     "alias": "VMIScheduled",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "vmiScheduledLatency",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "timestamp"
    },
    {
     "alias": "VMIScheduling",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "vmiSchedulingLatency",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "timestamp"
    },
    {
     "alias": "PodReady",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "podReadyLatency",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "timestamp"
    },
    {
     "alias": "PodContainersReady",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "podContainersReadyLatency",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "timestamp"
    },
    {
     "alias": "PodInitialized",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "podInitializedLatency",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "timestamp"
    },
    {
     "alias": "PodScheduled",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "podScheduledLatency",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "timestamp"
    },
    {
     "alias": "PodCreated",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "podCreatedLatency",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "timestamp"
    },
    {
     "alias": "VMIPending",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "vmiPendingLatency",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "timestamp"
    },
    {
     "alias": "VMICreated",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "vmiCreatedLatency",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VM Creation P99 Latency Breakdown",
   "type": "graph",
   "description": "If the VMI was created by a VM object, the VM creation time is the baseline timestamp, otherwise the VMI creation time is used as the baseline timestamp.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{term quantileName.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "quantileName.keyword",
       "id": "14",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "13", "size": "0" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "5m", "min_doc_count": "0", "offset": "", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "P99",
       "id": "13",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: vmiLatencyQuantilesMeasurement",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "VM Creation P50 Latency Breakdown",
   "type": "graph",
   "description": "If the VMI was created by a VM object, the VM creation time is the baseline timestamp, otherwise the VMI creation time is used as the baseline timestamp.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{term quantileName.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "quantileName.keyword",
       "id": "14",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "13", "size": "0" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "5m", "min_doc_count": "0", "offset": "", "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "P50",
       "id": "13",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: vmiLatencyQuantilesMeasurement",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "CNV (Kubevirt) API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "k8s APIServer P99 Response Latency for Read Requests",
   "type": "graph",
   "description": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{group=\"kubevirt.io\", verb=~\"LIST|GET\"}[2m])) by (verb,resource,subresource,instance,le)) > 0",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "{{labels.resource.keyword}}: {{labels.verb.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.verb.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.resource.keyword",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: kubevirtAPI99thReadRequestLatency",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "k8s APIServer P99 Response Latency for Write Requests",
   "type": "graph",
   "description": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{group=\"kubevirt.io\", verb=~\"POST|PUT|PATCH|DELETE\"}[2m])) by (verb,resource,subresource,instance,le)) > 0",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "{{labels.resource.keyword}}: {{labels.verb.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.verb.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.resource.keyword",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: kubevirtAPI99thWriteRequestLatency",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "k8s APIServer Response Count",
   "type": "graph",
   "description": "sum(increase(apiserver_request_total{group=~\".*kubevirt.*\"}[5m])) by (verb,group,resource,subresource,code) > 0",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{labels.resource.keyword}}: {{labels.verb.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.verb.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.resource.keyword",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: kubevirtAPIRequestCount",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "k8s APIServer Response Rate",
   "type": "graph",
   "description": "sum(irate(apiserver_request_total{group=~\".*kubevirt.*\"}[2m])) by (verb,group,resource,subresource,code) > 0",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "{{labels.resource.keyword}}: {{labels.verb.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.verb.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.resource.keyword",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: kubevirtAPIRequestRate",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "P99 kubevirt Rest Client Read Request Latency",
   "type": "graph",
   "description": "histogram_quantile(0.99, sum(rate(rest_client_request_duration_seconds_bucket{url=~\".*kubevirt.io.*\", verb=~\"LIST|GET\"}[2m])) by (verb,le,url)) > 0",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "{{labels.verb.keyword}}: {{labels.url.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.verb.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.url.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: kubevirtRestClient99thReadRequestLatency",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "kubevirt Rest Client Read Request Rate",
   "type": "graph",
   "description": "sum(irate(rest_client_requests_total{pod=~\"virt-controller.*|virt-handler.*|virt-operator.*|virt-api.*|vm.*|hco.*|kubevirt.*\"}[2m])) by (code, container, job, verb, method) > 0",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 50 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "{{labels.container.keyword}}:  {{labels.method.keyword}} - {{labels.code.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.container.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.method.keyword",
       "id": "6",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.code.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: kubevirtRestClientRequestRate AND ( labels.method.keyword:\"LIST\" OR  labels.method.keyword:\"GET\" OR  labels.method.keyword: \"WATCH\")",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "P99 kubevirt Rest Client Write Request Latency",
   "type": "graph",
   "description": "histogram_quantile(0.99, sum(rate(rest_client_request_duration_seconds_bucket{url=~\".*kubevirt.io.*\", verb=~\"POST|PUT|PATCH|DELETE\"}[2m])) by (verb,le,url)) > 0",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "{{labels.verb.keyword}}: {{labels.url.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.verb.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.url.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: kubevirtRestClient99thWriteRequestLatency",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "kubevirt Rest Client Write Request Rate",
   "type": "graph",
   "description": "sum(irate(rest_client_requests_total{pod=~\"virt-controller.*|virt-handler.*|virt-operator.*|virt-api.*|vm.*|hco.*|kubevirt.*\"}[2m])) by (code, container, job, verb, method) > 0",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 59 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "{{labels.container.keyword}}:  {{labels.method.keyword}} - {{labels.code.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.container.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.method.keyword",
       "id": "6",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.code.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: kubevirtRestClientRequestRate AND ( labels.method.keyword:\"POST\" OR  labels.method.keyword:\"PUT\" OR  labels.method.keyword: \"PATCH\" OR  labels.method.keyword: \"DELETE\")",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "kubevirt Rest Client Read Request Count",
   "type": "graph",
   "description": "sum(increase(rest_client_requests_total{pod=~\"virt-controller.*|virt-handler.*|virt-operator.*|virt-api.*|vm.*|hco.*|kubevirt.*\"}[5m])) by (code, container, job, verb, method) > 0",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{labels.container.keyword}}:  {{labels.method.keyword}} - {{labels.code.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.container.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.method.keyword",
       "id": "6",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.code.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: kubevirtRestClientRequestCount AND ( labels.method.keyword:\"LIST\" OR  labels.method.keyword:\"GET\" OR  labels.method.keyword: \"WATCH\")",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "kubevirt Rest Client Write Request Count",
   "type": "graph",
   "description": "sum(increase(rest_client_requests_total{pod=~\"virt-controller.*|virt-handler.*|virt-operator.*|virt-api.*|vm.*|hco.*|kubevirt.*\"}[5m])) by (code, container, job, verb, method) > 0",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{labels.container.keyword}}:  {{labels.method.keyword}} - {{labels.code.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.container.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.method.keyword",
       "id": "6",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.code.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: kubevirtRestClientRequestCount AND ( labels.method.keyword:\"POST\" OR  labels.method.keyword:\"PUT\" OR  labels.method.keyword: \"PATCH\" OR  labels.method.keyword: \"DELETE\")",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "kubevirt Rate Limiter P95 Duration",
   "type": "graph",
   "description": "histogram_quantile(0.95, sum(rate(rest_client_rate_limiter_duration_seconds_bucket{container!=\"\"}[5m])) by (container, service, le)) > 0",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "{{labels.container.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.container.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: kubevirtRateLimiter95thDuration",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "CNV (Kubevirt) WorkQueue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "kubevirt Workqueue Add Rate",
   "type": "graph",
   "description": "sum(rate(kubevirt_workqueue_adds_total{job=~\".*kubevirt.*\"}[1m])) by (instance, name) > 0",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "{{labels.name.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.name.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: kubevirtWorkQueueAddRate",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "kubevirt Workqueue Retry Rate",
   "type": "graph",
   "description": "sum(rate(kubevirt_workqueue_adds_total{job=~\".*kubevirt.*\"}[1m])) by (instance, name) > 0",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "{{labels.name.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.name.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: kubevirtWorkQueueRetryRate",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "kubevirt Workqueue P99 Wait Duration",
   "type": "graph",
   "description": "histogram_quantile(0.99, sum(rate(kubevirt_workqueue_queue_duration_seconds_bucket{job=~\".*kubevirt.*\"}[1m])) by (instance, name, le)) > 0",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "{{labels.name.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.name.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: kubevirtWorkQueue99thQueueDuration",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "kubevirt Workqueue P99 Work Duration",
   "type": "graph",
   "description": "histogram_quantile(0.99, sum(rate(kubevirt_workqueue_work_duration_seconds_bucket{job=~\".*kubevirt.*\"}[1m])) by (instance, name, le)) > 0",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "{{labels.name.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.name.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: kubevirtWorkQueue99thWorkDuration",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "kubevirt Workqueue Unfinished Work",
   "type": "graph",
   "description": "kubevirt_workqueue_unfinished_work_seconds{} > 0",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "{{labels.name.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.name.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: kubevirtWorkQueueUnfinishedWork",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "kubevirt Workqueue Longest Running Processor",
   "type": "graph",
   "description": "kubevirt_workqueue_longest_running_processor_seconds{} > 0",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "{{labels.name.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.name.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: kubevirtWorkQueueLongestRunningProcessor",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "kubevirt Workqueue Depth",
   "type": "graph",
   "description": "sum(rate(kubevirt_workqueue_adds_total{job=~\".*kubevirt.*\"}[1m])) by (instance, name) > 0",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "{{labels.name.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: kubevirtWorkQueueDepth",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "CNV (Kubevirt) Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 } },
  {
   "title": "kubevirt Process CPU Usage",
   "type": "graph",
   "description": "sum(irate(process_cpu_seconds_total{container!=\"\", job=~\".*kubevirt.*\"}[5m]) * 100) by (container, instance) > 0",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.container.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: kubevirtCPU",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "kubevirt Process RSS Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.container.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: kubevirtMemory",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Etcd", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 127 } },
  {
   "title": "etcd P99 disk WAL fsync latency",
   "type": "graph",
   "description": "histogram_quantile(0.99, rate(etcd_disk_wal_fsync_duration_seconds_bucket[2m])) > 0",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: 99thEtcdDiskWalFsyncDurationSeconds",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "etcd P99 disk backend commit latency",
   "type": "graph",
   "description": "histogram_quantile(0.99, rate(etcd_disk_backend_commit_duration_seconds_bucket[2m])) > 0",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 128 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: 99thEtcdDiskWalFsyncDurationSeconds",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "etcd P99 network peer roundtrip time",
   "type": "graph",
   "description": "histogram_quantile(0.99, rate(etcd_network_peer_round_trip_time_seconds_bucket[5m])) > 0",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 136 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: 99thEtcdRoundTripTimeSeconds",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Etcd P99 Request Latency",
   "type": "graph",
   "description": "histogram_quantile(0.99,sum(rate(etcd_request_duration_seconds_bucket[2m])) by (le,operation,apiserver)) > 0",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 136 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "{{labels.apiserver.keyword}}:  {{labels.operation.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.operation.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.apiserver.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: P99APIEtcdRequestLatency",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Etcd DB size",
   "type": "graph",
   "description": "etcd_mvcc_db_total_size_in_bytes > 0\netcd_mvcc_db_total_size_in_use_in_bytes > 0",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 144 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Physical size: {{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: etcdDBPhysicalSizeBytes",
     "timeField": "timestamp"
    },
    {
     "alias": "Logical size: {{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: etcdDBLogicalSizeBytes",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Etcd object count",
   "type": "graph",
   "description": "sum(rate(etcd_object_counts{}[5m])) by (resource) > 0",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 144 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "{{term labels.resource.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.resource.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "15" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: etcdObjectCount",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Etcd leader",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 152 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Etcd leader changes",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: etcdLeaderChangesRate",
     "timeField": "timestamp"
    },
    {
     "alias": "Current leader: {{term labels.pod.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: etcdServerIsLeader",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Etcd object count rate",
   "type": "graph",
   "description": "sum(rate(etcd_object_counts{}[5m])) by (resource) > 0",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 152 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "alias": "{{term labels.resource.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.resource.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "15" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: etcdObjectRate",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Golang metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 160 } },
  {
   "title": "Go Heap Alloc Bytes",
   "type": "graph",
   "description": "go_memstats_heap_alloc_bytes{job=~\"apiserver|api|etcd|kubevirt.*\"} > 0",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 161 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "{{labels.container.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.container.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"goHeapAllocBytes\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Go Heap Inuse Bytes",
   "type": "graph",
   "description": "go_memstats_heap_inuse_bytes{job=~\"apiserver|api|etcd|kubevirt.*\"} > 0",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 161 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "{{labels.container.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.container.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"goHeapInuseBytes\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Go GC Duration Rate",
   "type": "graph",
   "description": "sum(rate(go_gc_duration_seconds_sum{job=~\"apiserver|api|etcd|kubevirt.*\"}[5m])) by (container, instance) / sum(rate(go_gc_duration_seconds_count{job=~\"apiserver|api|etcd|kubevirt.*\"}[5m])) by (container, instance) > 0",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 169 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "{{labels.container.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.container.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"goGCDurationRate\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Go Routines Count",
   "type": "graph",
   "description": "go_goroutines{job=~\"apiserver|api|etcd|kubevirt.*\"} > 0",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 169 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{labels.container.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.container.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"goRoutinesCount\"",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "K8s API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 177 } },
  {
   "title": "Scheduling P99 Duration",
   "type": "graph",
   "description": "histogram_quantile(0.99, sum(rate(scheduler_e2e_scheduling_duration_seconds_bucket{}[5m])) by (le, pod))",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 178 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "{{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: 99thSchedulingDuration",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Scheduling Volume P99 Duration",
   "type": "graph",
   "description": "histogram_quantile(0.99, sum(rate(scheduler_volume_scheduling_duration_seconds_bucket{}[5m])) by (le, pod))",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 178 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "{{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: 99thSchedulingVolumeDuration",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "k8s WorkQueue Add Rate",
   "type": "graph",
   "description": "sum(irate(workqueue_adds_total{}[2m])) by (service, name) > 0",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 186 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "{{labels.service.keyword}}: {{labels.name.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.name.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "15" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.service.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: workQueueAddRate",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "k8s WorkQueue P99 Wait Duration",
   "type": "graph",
   "description": "histogram_quantile(0.99, sum(rate(workqueue_queue_duration_seconds_bucket{}[5m])) by (service, name, le)) > 0",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 194 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "{{labels.service.keyword}}: {{labels.name.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.name.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "15" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.service.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: workQueue99thQueueDuration",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "k8s WorkQueue Depth",
   "type": "graph",
   "description": "sum(irate(workqueue_adds_total{}[2m])) by (service, name) > 0",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 194 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{labels.service.keyword}}: {{labels.name.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.name.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "15" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.service.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: workQueueDepth",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "k8s WorkQueue Retry Rate",
   "type": "graph",
   "description": "sum(irate(workqueue_retries_total{}[5m])) by (service, name) > 0",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 202 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "{{labels.service.keyword}}: {{labels.name.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.name.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "15" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.service.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: workQueueRetryRate",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "k8s WorkQueue P99 Work Duration",
   "type": "graph",
   "description": "histogram_quantile(0.99, sum(rate(workqueue_work_duration_seconds_bucket{}[1m]))  by (service, name, le)) > 0",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 202 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "{{labels.service.keyword}}: {{labels.name.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.name.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "15" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.service.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: workQueue99thWorkDuration",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "k8s WorkQueue Unfinished Work",
   "type": "graph",
   "description": "sum(workqueue_unfinished_work_seconds) by (service, name) > 0",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 210 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "{{labels.service.keyword}}: {{labels.name.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.name.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "15" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.service.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: workQueueUnfinishedWork",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "k8s WorkQueue Longest Running Processor",
   "type": "graph",
   "description": "sum(workqueue_longest_running_processor_seconds{}) by (service, name) > 0",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 210 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "{{labels.service.keyword}}: {{labels.name.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.name.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "15" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.service.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: workQueueLongestRunningProcessor",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "k8s APIServer P99 Read Request Latency",
   "type": "graph",
   "description": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{group=\"kubevirt\", verb=~\"LIST|GET\"}[2m])) by (verb,resource,subresource,instance,le)) > 0",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 218 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "{{labels.resource.keyword}}: {{labels.verb.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.resource.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.verb.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: API99thReadRequestLatency",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "k8s APIServer Read Request Rate",
   "type": "graph",
   "description": "sum(irate(apiserver_request_total{}[2m])) by (verb,resource,subresource,apiserver,component,code) > 0",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 218 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "alias": "{{labels.resource.keyword}}: {{labels.verb.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.resource.keyword",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.verb.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: APIRequestRate AND ( labels.verb.keyword:\"LIST\" OR  labels.verb.keyword:\"GET\" OR  labels.verb.keyword: \"WATCH\")",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "k8s APIServer P99 Write Request Latency",
   "type": "graph",
   "description": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{apiserver=\"kube-apiserver\", verb=~\"POST|PUT|PATCH|DELETE\", subresource!=\"log\"}[2m])) by (verb,resource,subresource,instance,le)) > 0",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 226 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "{{labels.resource.keyword}}: {{labels.verb.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.resource.keyword",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.verb.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: API99thWriteRequestLatency",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "k8s APIServer Write Request Rate",
   "type": "graph",
   "description": "sum(irate(apiserver_request_total{}[2m])) by (verb,resource,subresource,apiserver,component,code) > 0",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 226 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "alias": "{{labels.resource.keyword}}: {{labels.verb.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.resource.keyword",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.verb.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: APIRequestRate AND ( labels.verb.keyword:\"POST\" OR  labels.verb.keyword:\"PUT\" OR  labels.verb.keyword: \"PATCH\" OR  labels.verb.keyword: \"DELETE\")",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "k8s APIServer Read Request Count",
   "type": "graph",
   "description": "sum(increase(apiserver_request_total{}[5m])) by (verb,resource,subresource,apiserver,component,code) > 0",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 234 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{labels.resource.keyword}}: {{labels.verb.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.resource.keyword",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.verb.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: APIRequestCount AND ( labels.verb.keyword:\"LIST\" OR  labels.verb.keyword:\"GET\" OR  labels.verb.keyword: \"WATCH\")",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "k8s APIServer Write Request Count",
   "type": "graph",
   "description": "sum(increase(apiserver_request_total{}[5m])) by (verb,resource,subresource,apiserver,component,code) > 0",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 234 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{labels.resource.keyword}}: {{labels.verb.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.resource.keyword",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.verb.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: APIRequestCount AND ( labels.verb.keyword:\"POST\" OR  labels.verb.keyword:\"PUT\" OR  labels.verb.keyword: \"PATCH\" OR  labels.verb.keyword: \"DELETE\")",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "k8s APIServer Inflight Request Rate",
   "type": "graph",
   "description": "sum(apiserver_current_inflight_requests{}) by (request_kind) > 0",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 242 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.request_kind.keyword",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: APIInflightRequests",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "k8s APIServer Flow Control Dispatched Request Rate",
   "type": "graph",
   "description": "sum(rate(apiserver_flowcontrol_dispatched_requests_total[2m])) by (flow_schema,priority_level) > 0",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 242 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "alias": "{{labels.flow_schema.keyword}}:  {{labels.priority_level.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.priority_level.keyword",
       "id": "5",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.flow_schema.keyword",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: flowControlRate",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "k8s APIServer P99 Flow Control Request Wait Latency",
   "type": "graph",
   "description": "histogram_quantile(0.99, sum(rate(apiserver_flowcontrol_request_wait_duration_seconds_bucket{}[5m])) by (le, flow_schema, priority_level)) > 0",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 251 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "{{labels.flow_schema.keyword}}:  {{labels.priority_level.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.priority_level.keyword",
       "id": "5",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.flow_schema.keyword",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: flowControl99thRequestWait",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "k8s APIServer P99 Flow Control Request Execution Latency",
   "type": "graph",
   "description": "histogram_quantile(0.99, sum(rate(apiserver_flowcontrol_request_execution_seconds_bucket{}[5m])) by (le, flow_schema, priority_level)) > 0",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 251 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "{{labels.flow_schema.keyword}}:  {{labels.priority_level.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.priority_level.keyword",
       "id": "5",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.flow_schema.keyword",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: flowControl99thRequestExecution",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Monitoring stack", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 260 } },
  {
   "title": "Prometheus CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 261 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.container.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: containerCPU-Prometheus",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Prometheus RSS Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 261 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "{{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.container.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: containerMemory-Prometheus",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Prometheus TSDB storage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 269 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "{{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: prometheus-tsdb-storage",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Cluster status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 277 } },
  {
   "title": "Node status summary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 278 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.condition.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"nodeStatus\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Pod status summary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 278 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.phase.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"podStatusCount\"",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Cluster Kubelet & CRI-O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 286 } },
  {
   "title": "Top 5 Kubelet process CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 287 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.node.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND (metricName.keyword: top3KubeletCPU OR metricName.keyword: kubeletCPU)",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top 5 Kubelet process RSS memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 287 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.node.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND (metricName.keyword: top3KubeletMemory OR metricName.keyword: kubeletMemory)",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Kubelet P99 Pod Start Duration",
   "type": "graph",
   "description": "histogram_quantile(0.99, sum(rate(kubelet_pod_start_duration_seconds_bucket{}[5m])) by (instance, le)) > 0",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 295 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "{{labels.instance.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.instance.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: kubelet99thPodStartDuration",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Kubelet P99 Pod Start Rate",
   "type": "graph",
   "description": "sum(rate(kubelet_pod_start_duration_seconds_count{}[5m])) by (node) > 0",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 295 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "{{labels.node.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.node.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: kubeletPodStartRate",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Kubelet P99 Pod Worker Duration",
   "type": "graph",
   "description": "histogram_quantile(0.99, sum(rate(kubelet_pod_worker_duration_seconds_bucket{}[5m])) by (node, le, operation_type)) > 0",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 303 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "{{labels.node.keyword}}: {{labels.operation_type.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.operation_type.keyword",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.node.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: kubelet99thPodWorkerDuration",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top Kubelet Storage Operation Error Rate",
   "type": "graph",
   "description": "sum(rate(storage_operation_errors_total{metrics_path=\"/metrics\"}[5m])) by (instance, node, operation_name, volume_plugin) > 0",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 303 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "{{labels.node.keyword}}: {{labels.volume_plugin.keyword}} - {{labels.operation_name.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.node.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.volume_plugin.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.operation_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND (metricName.keyword: kubeletStorageOperationErrorsCount OR metricName.keyword: kubeletStorageOperationErrorsRate)",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top Kubelet Storage Operations Rate",
   "type": "graph",
   "description": "sum(rate(storage_operation_duration_seconds_count{metrics_path=\"/metrics\"}[5m])) by (instance, operation_name, volume_plugin) > 0",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 311 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "{{labels.node.keyword}}: {{labels.volume_plugin.keyword}} - {{labels.operation_name.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.node.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.volume_plugin.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.operation_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND (metricName.keyword: kubeletStorageOperationCount OR  metricName.keyword: kubeletStorageOperationRate)",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top Kubelet Storage Operation Duration",
   "type": "graph",
   "description": "histogram_quantile(0.99, sum(rate(storage_operation_duration_seconds_bucket{metrics_path=\"/metrics\"}[5m])) by (le, node, operation_name, volume_plugin)) > 0.01",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 311 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "{{labels.node.keyword}}: {{labels.volume_plugin.keyword}} - {{labels.operation_name.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.node.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.volume_plugin.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.operation_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: kubeletStorageOperation99thDurationSeconds",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top 5 CRI-O process CPU usage",
   "type": "graph",
   "description": "sum(irate(process_cpu_seconds_total{service=\"kubelet\",job=\"crio\"}[2m]) * 100) by (node) and on (node) kube_node_role{role=\"worker\"} > 0",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 321 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.node.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND (metricName.keyword: top3CrioCPU OR metricName.keyword: crioCPU)",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top 5 CRI-O process RSS memory usage",
   "type": "graph",
   "description": "sum(process_resident_memory_bytes{service=\"kubelet\",job=\"crio\"}) by (node) and on (node) kube_node_role{role=\"worker\"} > 0",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 321 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.node.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND (metricName.keyword: top3CrioMemory OR metricName.keyword: crioMemory)",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top 5 process CPU usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 329 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{labels.container.keyword}} - {{labels.job.keyword}} : {{labels.instance.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.container.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.instance.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.job.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: processCPU",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top 5 process RSS memory usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 329 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "{{labels.container.keyword}} - {{labels.job.keyword}} : {{labels.instance.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.container.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.instance.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.job.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "uuid: $uuid AND metricName.keyword: processMemory",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Master: $master", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 340 } },
  {
   "title": "Top CPU  usage, master: $master",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 341 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{labels.node.keyword}}: {{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.node.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"podCPU\" AND labels.node.keyword:$master",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top 5 memory RSS, master: $master",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 341 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "{{labels.node.keyword}}: {{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "5",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.node.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"podMemory\" AND labels.node.keyword:$master",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Node CPU, master: $master",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 350 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{labels.instance.keyword}}: {{labels.mode.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.instance.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.mode.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "inlineScript": "_value*100",
       "meta": {},
       "settings": { "script": { "inline": "_value*100" } },
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"nodeCPU\" AND labels.instance.keyword:$master AND NOT labels.mode.keyword: \"idle\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Node Memory,  master: $master",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 350 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "{{labels.instance.keyword}}: cached+buffers",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.instance.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"nodeMemoryCached+nodeMemoryBuffers\" AND labels.instance.keyword: $master",
     "timeField": "timestamp"
    },
    {
     "alias": "{{labels.instance.keyword}}: active",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.instance.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"nodeMemoryActive\" AND labels.instance.keyword: $master",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Network bytes, master: $master",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 358 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "txNetworkBytes: {{labels.instance.keyword}} - {{labels.device.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.instance.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.device.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName: \"txNetworkBytes\"  AND labels.instance.keyword: $master",
     "timeField": "timestamp"
    },
    {
     "alias": "rxNetworkBytes {{labels.instance.keyword}} - {{labels.device.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.instance.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.device.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND  metricName: \"rxNetworkBytes\" AND labels.instance.keyword: $master",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Disk Throughput, master: $master",
   "type": "graph",
   "description": "sum(rate(node_disk_written_bytes_total{}[2m])) by (device, instance) > 0",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 358 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Written bytes: {{labels.instance.keyword}} - {{labels.device.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.instance.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.device.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName: \"nodeDiskWrittenBytes\" AND labels.instance.keyword: $master",
     "timeField": "timestamp"
    },
    {
     "alias": "Read bytes: {{labels.instance.keyword}} - {{labels.device.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.instance.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.device.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND  metricName: \"nodeDiskReadBytes\" AND labels.instance.keyword: $master",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Dropped packets, master: $master",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 367 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "txDroppedPackets: {{labels.instance.keyword}} {{labels.device.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.instance.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.device.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName: \"txDroppedPackets\" AND labels.instance.keyword: $master",
     "timeField": "timestamp"
    },
    {
     "alias": "rxDroppedPackets: {{labels.instance.keyword}} {{labels.device.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.instance.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.device.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName: \"rxDroppedPackets\" AND labels.instance.keyword: $master",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Disk IOPS, master: $master",
   "type": "graph",
   "description": "sum(rate(node_disk_reads_completed_total{}[2m])) by (device, instance) > 0\nsum(rate(node_disk_writes_completed_total{}[2m])) by (device, instance) > 0",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 367 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "Write IOPS: {{labels.instance.keyword}} - {{labels.device.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.instance.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.device.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName: \"nodeDiskWriteOpsSec\" AND labels.instance.keyword: $master",
     "timeField": "timestamp"
    },
    {
     "alias": "Read IOPS: {{labels.instance.keyword}} - {{labels.device.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.instance.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.device.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND  metricName: \"nodeDiskReadOpsSec\" AND labels.instance.keyword: $master",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top 5 Container FS Write Bytes, master: $master",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 375 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "{{labels.node.keyword}}: {{labels.container.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.container.keyword",
       "id": "5",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.node.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: containerDiskUsage  AND labels.node.keyword:$master",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top 5 Node  FS Usage, master: $master",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 375 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "{{labels.node.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.node.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: containerFsUsage AND labels.node.keyword:$master",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Worker: $worker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 384 } },
  {
   "title": "Top Pod CPU usage, worker: $worker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 385 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{labels.node.keyword}}: {{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.node.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.namespace.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 1 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"podCPU\" AND labels.node.keyword:$worker AND labels.namespace.keyword: $namespace",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top Pod Memory RSS, worker: $worker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 385 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "{{labels.node.keyword}}: {{labels.pod.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.node.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.pod.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"podMemory\" AND labels.node.keyword: $worker AND labels.namespace.keyword: $namespace",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Node CPU, worker: $worker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 394 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{labels.instance.keyword}} {{labels.mode.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.instance.keyword",
       "id": "5",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.mode.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "inlineScript": "_value*100",
       "meta": {},
       "settings": { "script": { "inline": "_value*100" } },
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"nodeCPU\" AND labels.instance.keyword: $worker AND NOT labels.mode.keyword: \"idle\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Node Memory: worker: $worker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 394 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "{{labels.instance.keyword}}: cached+buffers",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.instance.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"nodeMemoryCached+nodeMemoryBuffers\" AND labels.instance.keyword:  $worker",
     "timeField": "timestamp"
    },
    {
     "alias": "{{labels.instance.keyword}}: active",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.instance.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid.keyword: $uuid AND metricName: \"nodeMemoryActive\" AND labels.instance.keyword:  $worker",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Network bytes, worker: $worker",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 402 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "txNetworkBytes: {{labels.instance.keyword}} - {{labels.device.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.instance.keyword",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.device.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName: \"txNetworkBytes\" AND labels.instance.keyword: $worker",
     "timeField": "timestamp"
    },
    {
     "alias": "rxNetworkBytes {{labels.instance.keyword}} - {{labels.device.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.instance.keyword",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.device.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName: \"rxNetworkBytes\" AND labels.instance.keyword: $worker",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Disk Throughput, worker: $worker",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 402 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Written bytes: {{labels.instance.keyword}} - {{labels.device.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.instance.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.device.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName: \"nodeDiskWrittenBytes\" AND labels.instance.keyword: $worker",
     "timeField": "timestamp"
    },
    {
     "alias": "Read bytes {{labels.instance.keyword}} - {{labels.device.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.instance.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.device.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND  metricName: \"nodeDiskReadBytes\" AND labels.instance.keyword: $worker",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Dropped packets, worker: $worker",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 413 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "txDroppedPackets - {{labels.instance.keyword}} {{labels.device.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.instance.keyword",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.device.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName: txDroppedPackets AND labels.instance.keyword: $worker",
     "timeField": "timestamp"
    },
    {
     "alias": "rxDroppedPackets - {{labels.instance.keyword}} {{labels.device.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.instance.keyword",
       "id": "4",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.device.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName: rxDroppedPackets AND labels.instance.keyword: $worker",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Disk IOPS, worker: $worker",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 413 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "Write IOPS:  {{labels.instance.keyword}} - {{labels.device.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.instance.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.device.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND metricName: \"nodeDiskWriteOpsSec\" AND labels.instance.keyword: $worker",
     "timeField": "timestamp"
    },
    {
     "alias": "Read IOPS: {{labels.instance.keyword}} - {{labels.device.keyword}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "labels.instance.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "labels.device.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": "1", "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "uuid: $uuid AND  metricName: \"nodeDiskReadOpsSec\" AND labels.instance.keyword: $worker",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}