apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kubeburners{{.Iteration}}.cloudbulldozer.example.com
spec:
  group: cloudbulldozer.example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                workload:
                  type: string
                iterations:
                  type: integer
  scope: Cluster
  names:
    plural: kubeburners{{.Iteration}}
    singular: kubeburner{{.Iteration}}
    kind: KubeBurner{{.Iteration}}
    shortNames:
    - kb{{.Iteration}}

