---
global:
  indexerConfig:
    esServers: [http://elastic-elk.apps.rsevilla.kube-burner.com]
    insecureSkipVerify: true
    defaultIndex: kube-burner
    type: elastic
  measurements:
    - name: podLatency
    - name: pprof
      pprofInterval: 2m
      pprofDirectory: pprof-data
      pprofTargets:
      - name: ovnkube-controller
        namespace: "openshift-ovn-kubernetes"
        labelSelector: {app: ovnkube-node}
        url: http://localhost:29103/debug/pprof/profile?seconds=30
      - name: ovnk-control-plane
        namespace: "openshift-ovn-kubernetes"
        labelSelector: {app: ovnkube-control-plane}
        url: http://localhost:29108/debug/pprof/profile?seconds=30


jobs:
  - name: udn-density-l3-pods
    namespace: udn-density-l3-pods
    jobIterations: 72
    qps: 20
    burst: 20
    namespacedIterations: true
    podWait: false
    waitWhenFinished: true
    preLoadImages: false
    preLoadPeriod: 15s
    jobPause: 5m
    namespaceLabels:
      security.openshift.io/scc.podSecurityLabelSync: false
      pod-security.kubernetes.io/enforce: privileged
      pod-security.kubernetes.io/audit: privileged
      pod-security.kubernetes.io/warn: privileged
      k8s.ovn.org/primary-user-defined-network: ""
    objects:

      - objectTemplate: udn_l3.yml
        replicas: 1

      - objectTemplate: np-deny-all.yml
        replicas: 1

      - objectTemplate: np-allow-from-clients.yml
        replicas: 1

      - objectTemplate: service.yml
        replicas: 5

      - objectTemplate: deployment-server.yml
        replicas: 3
        inputVars:
          podReplicas: 2

      - objectTemplate: deployment-client.yml
        replicas: 2
        inputVars:
          podReplicas: 2
