# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - ppc64
    ldflags:
      - -X github.com/cloud-bulldozer/kube-burner/version.GitCommit={{.Commit}} -X github.com/cloud-bulldozer/kube-burner/version.BuildDate={{.Date}} -X github.com/cloud-bulldozer/kube-burner/version.Version={{.Version}}
archives:
  - name_template: "kube-burner-{{.Version}}-{{.Os}}-{{.Arch}}"
    format: tar.gz
    format_overrides:
    - goos: windows
      format: zip
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - LICENSE
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
checksum:
  name_template: "kube-burner-checksums.txt"
