# Labels for labeling issues and pull requests using GitHub prow action.

area:
  - 'area/performance'
  - 'area/scalability'
  - 'area/observability'
  - 'area/ci'
  - 'area/deployment'
  - 'area/operator'
  - 'area/networking'
  - 'area/storage'
  - 'area/tests'
  - 'area/cleanup'
  - 'area/docs'
  - 'area/security'
  - 'area/k8s'

kind:
  - 'bug'
  - 'security'
  - 'feature'
  - 'docs'
  - 'cleanup'
  - 'test'
  - 'enhancement'
  - 'infrastructure'
  - 'performance'
  - 'ci'

priority:
  - 'P0'
  - 'P1'
  - 'P2'