# Labels for labeling issues and pull requests using GitHub prow action.

area:
  - 'performance'
  - 'scalability'
  - 'observability'
  - 'deployment'
  - 'operator'
  - 'networking'
  - 'storage'
  - 'cleanup'
  - 'docs'
  - 'security'
  - 'k8s'

kind:
  - 'bug'
  - 'security'
  - 'feature'
  - 'docs'
  - 'cleanup'
  - 'test'
  - 'enhancement'
  - 'ci'
  - 'refactor'
  - 'breaking'

priority:
  - 'P0'
  - 'P1'
  - 'P2'