docs_dir: docs/
repo_url: https://github.com/kube-burner/kube-burner
nav:
- Home: index.md
- Command line: cli.md
- Reference: reference/configuration.md
- Measurements: measurements.md
- Observability & Alerting: 
  - observability/index.md
  - Overview: observability/index.md
  - Collecting metrics: observability/metrics.md
  - Indexing: observability/indexing.md
  - Alerting: observability/alerting.md
- Contributing:
  - contributing/index.md
  - GitHub Workflows:
    - contributing/pullrequest.md
    - contributing/release.md
  - Tests: contributing/tests.md
site_name: Kube-burner
plugins:
  - search
  - include-markdown
extra:
  social:
    - icon: fontawesome/brands/slack
      link: https://slack.cncf.io
    - icon: fontawesome/brands/github
      link: https://github.com/kube-burner
  version:
    provider: mike
    limit: 3
extra_css:
  - css/extra.css
theme:
  version: latest
  name: material
  custom_dir: docs/overrides
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    # Palette toggle for light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: indigo
      toggle:
        icon: material/weather-sunny

  logo: media/logos/kube-burner-logo-mini.png
  favicon: media/logos/kube-burner-logo-mini.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
copyright: Copyright © 2024 The kube-burner Authors</br></br>
