---
kind: Build
apiVersion: build.openshift.io/v1
metadata:
  name: {{.JobName}}-{{.Replica}}
spec:
  resources:
    requests:
      cpu: 10m
      memory: "10Mi"
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  serviceAccount: builder
  source:
    dockerfile: |-
      FROM registry.fedoraproject.org/fedora-minimal:latest
      RUN touch $(date +%s)
    type: Dockerfile
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: registry.fedoraproject.org/fedora-minimal:latest
    type: Source
  output:
    to:
      kind: ImageStreamTag
      name: cluster-density-{{.Replica}}:latest
