---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: server-{{.Replica}}
spec:
  replicas: {{.podReplicas}}
  selector:
    matchLabels:
      app: cluster-density-{{.Replica}}
  template:
    metadata:
      labels:
        app: cluster-density-{{.Replica}}
        name: nginx
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: Exists
              - key: node-role.kubernetes.io/infra
                operator: DoesNotExist
              - key: node-role.kubernetes.io/workload
                operator: DoesNotExist
      containers:
      - image: quay.io/cloud-bulldozer/nginx:latest
        resources:
          requests:
            memory: "25Mi"
            cpu: "25m"
        volumeMounts:
        - name: secret-1
          mountPath: /secret1
        - name: secret-2
          mountPath: /secret2
        - name: secret-3
          mountPath: /secret3
        - name: secret-4
          mountPath: /secret4
        - name: configmap-1
          mountPath: /configmap1
        - name: configmap-2
          mountPath: /configmap2
        - name: configmap-3
          mountPath: /configmap3
        - name: configmap-4
          mountPath: /configmap4
        - name: podinfo
          mountPath: /etc/podlabels
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        name: cluster-density
        env:
        - name: ENVVAR1
          value: "{{randAlphaNum 250}}"
        - name: ENVVAR2
          value: "{{randAlphaNum 250}}"
        - name: ENVVAR3
          value: "{{randAlphaNum 250}}"
        - name: ENVVAR4
          value: "{{randAlphaNum 250}}"
      volumes:
      - name: secret-1
        secret:
          secretName: {{.JobName}}-1
      - name: secret-2
        secret:
          secretName: {{.JobName}}-2
      - name: secret-3
        secret:
          secretName: {{.JobName}}-3
      - name: secret-4
        secret:
          secretName: {{.JobName}}-4
      - name: configmap-1
        configMap:
          name: {{.JobName}}-1
      - name: configmap-2
        configMap:
          name: {{.JobName}}-2
      - name: configmap-3
        configMap:
          name: {{.JobName}}-3
      - name: configmap-4
        configMap:
          name: {{.JobName}}-4
      - name: podinfo
        downwardAPI:
          items:
            - path: "labels"
              fieldRef:
                fieldPath: metadata.labels
