kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-from-clients-{{.Replica}}
spec:
  podSelector:
    matchLabels:
      name: nginx
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: cluster-density-v2-{{.Iteration}}
      podSelector:
        matchLabels:
          name: client
  - ports:
    - protocol: TCP
      port: 8080
