---
kind: Service
apiVersion: v1
metadata:
  name: cluster-density-{{.Replica}}
spec:
  selector:
    name: nginx
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
