---
global:
  gc: {{.GC}}
  gcMetrics: {{.GC_METRICS}}
  indexerConfig:
    esServers: ["{{.ES_SERVER}}"]
    insecureSkipVerify: true
    defaultIndex: {{.ES_INDEX}}
    type: {{.INDEXING_TYPE}}
  measurements:
    - name: podLatency
jobs:
  - name: create-bindings
    namespace: networkpolicy-matchlabels
    skipIndexing: true
    jobIterations: 1
    objects:
      - objectTemplate: ../clusterrole.yml
        replicas: 1
      - objectTemplate: ../clusterrolebinding.yml
        replicas: 1

  - name: networkpolicy-matchlabels
    namespace: networkpolicy-matchlabels
    jobIterations: {{.JOB_ITERATIONS}}
    qps: {{.QPS}}
    burst: {{.BURST}}
    namespacedIterations: true
    podWait: false
    waitWhenFinished: true
    preLoadImages: true
    preLoadPeriod: 15s
    churn: {{.CHURN}}
    churnDuration: {{.CHURN_DURATION}}
    churnPercent: {{.CHURN_PERCENT}}
    churnDelay: {{.CHURN_DELAY}}
    churnDeletionStrategy: {{.CHURN_DELETION_STRATEGY}}
    namespaceLabels:
      security.openshift.io/scc.podSecurityLabelSync: false
      pod-security.kubernetes.io/enforce: privileged
      pod-security.kubernetes.io/audit: privileged
      pod-security.kubernetes.io/warn: privileged

    objects:
      - objectTemplate: deny-all.yml
        replicas: 1

      - objectTemplate: matchlabels-networkpolicy.yml
        replicas: 20
        inputVars:
          podselector_label_num: "label1"
          podselector_label: "foo"
          ingress_label_num: "label1"
          ingress_label: "foo"

      - objectTemplate: matchlabels-networkpolicy.yml
        replicas: 20
        inputVars:
          podselector_label_num: "label2"
          podselector_label: "bar"
          ingress_label_num: "label2"
          ingress_label: "bar"

      - objectTemplate: scraper.yml
        replicas: 20
        inputVars:
          label1: "foo"
          label2: "bar"
          workload: "networkpolicy-matchlabels"
          es_server: "{{.ES_SERVER}}"
          es_index: "networkpolicy-enforcement"
          set: "1"

      - objectTemplate: scraper.yml
        replicas: 20
        inputVars:
          label1: "foo"
          label2: "bar"
          workload: "networkpolicy-matchlabels"
          es_server: "{{.ES_SERVER}}"
          es_index: "networkpolicy-enforcement"
          set: "2"

      - objectTemplate: scraper.yml
        replicas: 20
        inputVars:
          label1: "foo"
          label2: "bar"
          workload: "networkpolicy-matchlabels"
          es_server: "{{.ES_SERVER}}"
          es_index: "networkpolicy-enforcement"
          set: "3"

      - objectTemplate: scraper.yml
        replicas: 20
        inputVars:
          label1: "foo"
          label2: "bar"
          workload: "networkpolicy-matchlabels"
          es_server: "{{.ES_SERVER}}"
          es_index: "networkpolicy-enforcement"
          set: "4"

      - objectTemplate: scraper.yml
        replicas: 20
        inputVars:
          label1: "foo"
          label2: "bar"
          workload: "networkpolicy-matchlabels"
          es_server: "{{.ES_SERVER}}"
          es_index: "networkpolicy-enforcement"
          set: "5"
