services:
  prometheus:
    image: prom/prometheus:v2.51.0
    container_name: keda-prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    extra_hosts:
      # This allows Prometheus to reach localhost on the host machine
      - "host.docker.internal:host-gateway"
