global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'keda-operator'
    metrics_path: /metrics
    static_configs:
      # host.docker.internal allows Docker to reach the port-forwarded KEDA on your localhost
      - targets: ['host.docker.internal:8080']

  - job_name: 'kube-state-metrics'
    metrics_path: /metrics
    static_configs:
      # Optional: if you port-forward kube-state-metrics to 8081
      - targets: ['host.docker.internal:8081']
