kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-list-crb-1
subjects:
- kind: Group
  name: system:authenticated
roleRef:
  kind: ClusterRole
  name: pods-list-1
  apiGroup: rbac.authorization.k8s.io

