---
global:
  measurements:
    - name: podLatency

jobs:
  - name: deny-all-policy
    jobIterations: 1
    qps: 1
    burst: 1
    namespacedIterations: false
    namespace: kubelet-density-cni-networkpolicy
    jobPause: 1m
    objects:

      - objectTemplate: templates/deny-all.yml
        replicas: 1

  - name: kubelet-density-cni-networkpolicy
    jobIterations: 100
    qps: 25
    burst: 25
    namespacedIterations: false
    namespace: kubelet-density-cni-networkpolicy
    waitWhenFinished: true
    podWait: false
    preLoadImages: true
    preLoadPeriod: 2m
    objects:

      - objectTemplate: templates/webserver-deployment.yml
        replicas: 1

      - objectTemplate: templates/webserver-service.yml
        replicas: 1

      - objectTemplate: templates/allow-http.yml
        replicas: 1

      - objectTemplate: templates/curl-deployment.yml
        replicas: 1
