# apiVersion: v1
# kind: Pod
# metadata:
#   name: test-pod
#   namespace: test-ns
# spec:
#   containers:
#   - name: busybox
#     image: busybox
#     command: ["sleep", "3600"]

apiVersion: v1
kind: Pod
metadata:
  name: example-pod
spec:
  containers:
    - name: pause
      image: k8s.gcr.io/pause
