---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-server-{{.Replica}}-{{.Iteration}}
spec:
  replicas: {{.podReplicas}}
  selector:
    matchLabels:
      app: nginx-server-{{.Replica}}-{{.Iteration}}
  template:
    metadata:
      labels:
        app: nginx-server-{{.Replica}}-{{.Iteration}}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: Exists
              - key: node-role.kubernetes.io/infra
                operator: DoesNotExist
              - key: node-role.kubernetes.io/workload
                operator: DoesNotExist
      containers:
      - image: quay.io/cloud-bulldozer/nginx:latest
        resources:
          requests:
            memory: "10Mi"
            cpu: "5m"
        volumeMounts:
        - name: podinfo
          mountPath: /etc/podlabels
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        name: server
        env:
        - name: ENVVAR1
          value: "{{randAlphaNum 250}}"
        - name: ENVVAR2
          value: "{{randAlphaNum 250}}"
        - name: ENVVAR3
          value: "{{randAlphaNum 250}}"
        - name: ENVVAR4
          value: "{{randAlphaNum 250}}"
      volumes:
      - name: podinfo
        downwardAPI:
          items:
            - path: "labels"
              fieldRef:
                fieldPath: metadata.labels
