kind: Deployment
apiVersion: apps/v1
metadata:
  name: http-client-{{.Replica}}-{{.Iteration}}
spec:
  replicas: {{.podReplicas}}
  selector:
    matchLabels:
      app: http-client-{{.Replica}}-{{.Iteration}}
  template:
    metadata:
      labels:
        app: http-client-{{.Replica}}-{{.Iteration}}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: Exists
              - key: node-role.kubernetes.io/infra
                operator: DoesNotExist
              - key: node-role.kubernetes.io/workload
                operator: DoesNotExist
      containers:
      - name: client-app
        image: quay.io/cloud-bulldozer/curl:latest
        command: ["sleep", "inf"]
        resources:
          requests:
            memory: "5Mi"
            cpu: "10m"
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: false
        readinessProbe:
          exec:
            command:
            - "/bin/sh"
            - "-c"
            - "curl --fail -sS ${SERVICE_ENDPOINT} -o /dev/null && curl --fail -sSk ${ROUTE_ENDPOINT} -o /dev/null"
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 6
        volumeMounts:
        - name: podinfo
          mountPath: /etc/podlabels
        env:
        - name: ENVVAR1
          value: "{{randAlphaNum 250}}"
        - name: ENVVAR2
          value: "{{randAlphaNum 250}}"
        - name: ENVVAR3
          value: "{{randAlphaNum 250}}"
        - name: ENVVAR4
          value: "{{randAlphaNum 250}}"
        - name: ROUTE_ENDPOINT
          value: "https://{{.JobName}}-{{.Replica}}-{{.Iteration}}-{{.Namespace}}.{{.ingressDomain}}/2048.html"
        - name: SERVICE_ENDPOINT
          value: "http://{{.JobName}}-{{.Replica}}-{{.Iteration}}/8192.html"
      volumes:
      - name: podinfo
        downwardAPI:
          items:
            - path: "labels"
              fieldRef:
                fieldPath: metadata.labels
      restartPolicy: Always
  strategy:
    type: RollingUpdate

