kind: Pod
apiVersion: v1
metadata:
  labels:
    name: node-density-{{.Iteration}}
    app: pause
  name: {{.JobName}}-{{.Iteration}}
spec:
  topologySpreadConstraints:
  - maxSkew: 1 
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway 
    labelSelector: 
      matchLabels:
        app: pause
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/worker
            operator: Exists
          - key: node-role.kubernetes.io/infra
            operator: DoesNotExist
          - key: node-role.kubernetes.io/workload
            operator: DoesNotExist
  tolerations:
  - key: os
    value: Windows
    effect: NoSchedule
  containers:
  - image: {{.containerImage}}
    name: node-density
    resources:
      requests:
        memory: "10Mi"
        cpu: "10m"
    imagePullPolicy: IfNotPresent
