---
kind: Service
apiVersion: v1
metadata:
  name: {{.name}}-{{.Iteration}}-{{.Replica}}
spec:
  selector:
    app: {{.name}}-{{.Iteration}}-{{.Replica}}
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8443
  type: ClusterIP
