kind: Service
apiVersion: v1
metadata:
  name: nginx-service-{{.Replica}}-{{.Iteration}}-{{.set}}
spec:
  selector:
    label1: {{.label1}}-{{.Replica}}
    label2: {{.label2}}-{{.Replica}}
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
