apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-{{.Iteration}}
  labels:
    pv-group: "{{.Iteration}}"
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  hostPath:
    path: /tmp/pv-{{.Iteration}}

