---
global:
  gc: {{.GC}}
  gcMetrics: {{.GC_METRICS}}
  indexerConfig:
    esServers: ["{{.ES_SERVER}}"]
    insecureSkipVerify: true
    defaultIndex: {{.ES_INDEX}}
    type: {{.INDEXING_TYPE}}
  measurements:
    - name: podLatency
      thresholds:
        - conditionType: Ready
          metric: P99
          threshold: {{.POD_READY_THRESHOLD}}
jobs:
  - name: cluster-density-ms
    namespace: cluster-density-ms
    jobIterations: {{.JOB_ITERATIONS}}
    qps: {{.QPS}}
    burst: {{.BURST}}
    namespacedIterations: true
    podWait: false
    waitWhenFinished: true
    preLoadImages: true
    preLoadPeriod: 10s
    churn: {{.CHURN}}
    churnDuration: {{.CHURN_DURATION}}
    churnPercent: {{.CHURN_PERCENT}}
    churnDelay: {{.CHURN_DELAY}}
    churnDeletionStrategy: {{.CHURN_DELETION_STRATEGY}}
    namespaceLabels:
      security.openshift.io/scc.podSecurityLabelSync: false
      pod-security.kubernetes.io/enforce: privileged
      pod-security.kubernetes.io/audit: privileged
      pod-security.kubernetes.io/warn: privileged
    objects:

      - objectTemplate: imagestream.yml
        replicas: 1

      - objectTemplate: deployment.yml
        replicas: 4
        inputVars:
          podReplicas: 2

      - objectTemplate: service.yml
        replicas: 2
        
      - objectTemplate: route.yml
        replicas: 1

      - objectTemplate: secret.yml
        replicas: 20

      - objectTemplate: configmap.yml
        replicas: 10
