---
apiVersion: v1
kind: Service
metadata:
  name: served-ns-{{ .ns }}-{{ .Replica }}
  labels:
    app: app-served-{{ .ns }}
spec:
  ports:
  - name: served-ns-{{ .ns }}-{{ .Replica }}
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: app-served-{{ .ns }}
