---
kind: Deployment
apiVersion: apps/v1
metadata:    
  name: dep-served-{{ .ns }}-{{ .Replica }}
spec:
  template:
    metadata:
      name: pod-served-{{ .ns }}-{{ .Replica }}
      labels:
        app: app-served-{{ .ns }}
    spec:
      containers:
      - name: sleep-1
        imagePullPolicy: IfNotPresent
        image: gcr.io/google_containers/pause-amd64:3.0
      - name: app-served-{{ .ns }}
        imagePullPolicy: IfNotPresent
        image: rhscl/httpd-24-rhel7:latest
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: '100Mi'
            cpu: 100m
          limits:
            memory: '100Mi'
            cpu: 100m
        env:
        - name: service_name
          value: app-served-{{ .ns }}
            #  nodeSelector:
            #     kubernetes.io/hostname: worker{{if eq .Iteration 81}}{{printf "%03d" (add .Iteration 2)}}{{else if eq .Iteration 82}}{{printf "%03d" (add .Iteration 1)}}{{else if eq .Iteration 98}}{{printf "%03d" (add .Iteration 2)}}{{else if eq .Iteration 110}}{{printf "%03d" (add .Iteration 2)}}{{else}}{{printf "%03d" (add .Iteration 3)}}{{end}}-r640       
  replicas: 1
  selector:
    matchLabels:
     app: app-served-{{ .ns }}
  strategy:
    type: RollingUpdate 
