---
apiVersion: v1
kind: Service
metadata:
  name: served-ns-{{ .ns }}-{{ .Replica }}
  labels:
    app: app-served-{{ .ns }}
spec:
  ports:
  - name: served-ns-{{ .ns }}-{{ .Replica }}-1
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: served-ns-{{ .ns }}-{{ .Replica }}-2
    port: 8081
    protocol: TCP
    targetPort: 8081
  - name: served-ns-{{ .ns }}-{{ .Replica }}-3
    port: 8082
    protocol: TCP
    targetPort: 8082
  - name: served-ns-{{ .ns }}-{{ .Replica }}-4
    port: 8083
    protocol: TCP
    targetPort: 8083
  - name: served-ns-{{ .ns }}-{{ .Replica }}-5
    port: 8084
    protocol: TCP
    targetPort: 8084
  - name: served-ns-{{ .ns }}-{{ .Replica }}-6
    port: 8085
    protocol: TCP
    targetPort: 8085
  - name: served-ns-{{ .ns }}-{{ .Replica }}-7
    port: 8086
    protocol: TCP
    targetPort: 8086
  - name: served-ns-{{ .ns }}-{{ .Replica }}-8
    port: 8087
    protocol: TCP
    targetPort: 8087
  - name: served-ns-{{ .ns }}-{{ .Replica }}-9
    port: 8088
    protocol: TCP
    targetPort: 8088
  - name: served-ns-{{ .ns }}-{{ .Replica }}-10
    port: 8089
    protocol: TCP
    targetPort: 8089
  - name: served-ns-{{ .ns }}-{{ .Replica }}-11
    port: 8090
    protocol: TCP
    targetPort: 8090
  - name: served-ns-{{ .ns }}-{{ .Replica }}-12
    port: 8091
    protocol: TCP
    targetPort: 8091
  - name: served-ns-{{ .ns }}-{{ .Replica }}-13
    port: 8092
    protocol: TCP
    targetPort: 8092
  - name: served-ns-{{ .ns }}-{{ .Replica }}-14
    port: 8093
    protocol: TCP
    targetPort: 8093
  - name: served-ns-{{ .ns }}-{{ .Replica }}-15
    port: 8094
    protocol: TCP
    targetPort: 8094
  selector:
    app: app-served-{{ .ns }}
