---
global:
  gc: true
  measurements:
    - name: podLatency

jobs:
  - name: kubelet-density-heavy
    jobIterations: 10
    qps: 10
    burst: 10
    namespacedIterations: false
    namespace: kubelet-density-heavy
    waitWhenFinished: true
    preLoadImages: false
    podWait: false
    objects:

      - objectTemplate: templates/postgres-deployment.yml
        replicas: 1

      - objectTemplate: templates/app-deployment.yml
        replicas: 1
        inputVars:
          readinessPeriod: 10

      - objectTemplate: templates/postgres-service.yml
        replicas: 1
