---
global:
  writeToFile: true
  metricsDirectory: collected-metrics
  indexerConfig:
    enabled: false
    esServers: [http://elastic-elk.apps.rsevilla.kube-burner.com]
    insecureSkipVerify: true
    defaultIndex: kube-burner
    type: elastic
  measurements:
    - name: podLatency
      esIndex: kube-burner
      thresholds:
        - conditionType: Ready
          metric: Avg
          threshold: 4s

jobs:
  - name: kubelet-density-heavy
    jobIterations: 3500 # each node cost 7.5 iteration
    qps: 25
    burst: 25
    namespacedIterations: false
    namespace: kubelet-density-heavy
    waitWhenFinished: true
    podWait: false
    objects:
      - objectTemplate: templates/postgres-deployment.yml
        replicas: 1
      - objectTemplate: templates/app-deployment.yml
        replicas: 1
        inputVars:
          readinessPeriod: 10
      - objectTemplate: templates/postgres-service.yml
        replicas: 1
