kind: Pod
apiVersion: v1
metadata:
  name: kubelet-density-{{.Iteration}}
  labels:
    name: kubelet-density
spec:
  containers:
  - name: kubelet-density
    image: {{.containerImage}}
    ports:
    - containerPort: 8080
      protocol: TCP
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "2"
        memory: "8Gi"
      limits:
        cpu: "2"
        memory: "8Gi"
    securityContext:
      privileged: false
  tolerations:
    - effect: NoSchedule
      key: node_type
      operator: Equal
      value: ondemand_m5_8x_asg
