{{- /* We use the replica number as a 0 based offset from the     }}
{{-    current namespace to a target namespace traffic is allowed }}
{{-    from. We also document the corresponding namespace traffic }}
{{-    is allowed to from this namespace as an un-enforced egress }}
{{-    rule.                                                      }}
{{-    Examples for 4 total namespaces/iterations:                }}
{{-    * current ns 2, replica 1, from ns 2, to ns 2              }}
{{-    * current ns 2, replica 2, from ns 3, to ns 1              }}
{{-    * current ns 2, replica 3, from ns 4, to ns 4              }}
{{-    * current ns 2, replica 4, from ns 1, to ns 3            */}}
{{- $v := sub .Replica 1 }}
{{- $v = mod $v .job_iterations }}
{{- $from := add .Iteration $v }}
{{- $job_iterations_sub1 := sub .job_iterations 1 }}
{{- if gt $from $job_iterations_sub1 }}
{{- $from = mod $from .job_iterations }}
{{- end }}
{{- $w := sub .Iteration $v }}
{{- $to := add .job_iterations $w }}
{{- if gt $to $job_iterations_sub1 }}
{{- $to = $w }}
{{- end }}
{{- $from_namespace := print "networkpolicy-multitenant-" $from }}
{{- $to_namespace := print  "networkpolicy-multitenant-" $to }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: multitenant-allow-from-{{$from_namespace}}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{$from_namespace}}
  # non enforcing egress, but provided as information to pod_scraper
  # to know which namespaces it is allowed to connect
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{$to_namespace}}
