apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: matchexpressions-{{.podselector_label}}{{.Replica}}-{{.ingress_label}}
spec:
  podSelector:
    matchLabels:
      {{.podselector_label_num}}: {{.podselector_label}}-{{.Replica}}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchExpressions:
           - key: {{.ingress_label_num}}
             operator: NotIn
             values: [{{.ingress_label}}-{{randInt 1 6}}]
