apiVersion: v1
kind: Pod
metadata:
  name: scraper-{{.Replica}}-{{.Iteration}}-{{.set}}
  labels:
    label1: {{.label1}}-{{.Replica}}
    label2: {{.label2}}-{{.Replica}}
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/worker
            operator: Exists
          - key: node-role.kubernetes.io/infra
            operator: DoesNotExist
          - key: node-role.kubernetes.io/workload
            operator: DoesNotExist
  containers:
  - name: scraper
    image: quay.io/cloud-bulldozer/netpol-scraper:latest
    imagePullPolicy: Always
    command: [ "/bin/bash", "-c", "--" ]
    args:
    - date;
      sh init.sh;
      sleep inf
    ports:
    - containerPort: 8080
    volumeMounts:
      - name: podinfo
        mountPath: /etc/podinfo
    env:
    - name: WORKLOAD
      value: {{.workload}}
    - name: ES_SERVER
      value: {{.es_server}}
    - name: ES_INDEX_NETPOL
      value: {{.es_index}}
  volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
