kind: Pod
apiVersion: v1
metadata:
  labels:
    app: pvc-density-{{.Iteration}}
  name: pod-{{.Iteration}}
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/worker
            operator: Exists
          - key: node-role.kubernetes.io/infra
            operator: DoesNotExist
          - key: node-role.kubernetes.io/workload
            operator: DoesNotExist
  tolerations:
  - key: os
    value: Windows
    effect: NoSchedule
  volumes:
    - name: storage-stress-vlm-{{.Iteration}}
      persistentVolumeClaim:
        claimName: pvc-{{.Iteration}}
  containers:
  - image: {{.containerImage}}
    name: pvc-density-container
    resources:
      requests:
        memory: "10Mi"
        cpu: "10m"
    imagePullPolicy: IfNotPresent
