---
global:
  gc: {{.GC}}
  indexerConfig:
    esServers: ["{{.ES_SERVER}}"]
    insecureSkipVerify: true
    defaultIndex: {{.ES_INDEX}}
    type: {{.INDEXING_TYPE}}
  measurements:
    - name: podLatency

jobs:
  - name: add-default-storage
    namespace: pvc-density
    jobIterations: 1
    namespacedIterations: false
    podWait: false
    waitWhenFinished: true
    skipIndexing: true
    namespaceLabels:
      security.openshift.io/scc.podSecurityLabelSync: false
      pod-security.kubernetes.io/enforce: privileged
      pod-security.kubernetes.io/audit: privileged
      pod-security.kubernetes.io/warn: privileged
    objects:

      - objectTemplate: storageclass.yml
        inputVars:
          storageProvisioner: {{.STORAGE_PROVISIONER}}
        replicas: 1

  - name: pvc-density
    namespace: pvc-density
    jobIterations: {{.JOB_ITERATIONS}}
    cleanup: true
    namespacedIterations: false
    podWait: false
    waitWhenFinished: true
    preLoadImages: true
    preLoadPeriod: 10s
    namespaceLabels:
      security.openshift.io/scc.podSecurityLabelSync: false
      pod-security.kubernetes.io/enforce: privileged
      pod-security.kubernetes.io/audit: privileged
      pod-security.kubernetes.io/warn: privileged
    objects:

      - objectTemplate: pvc.yml
        replicas: 1
        inputVars:
          claimSize: {{.CLAIM_SIZE}}

      - objectTemplate: pod.yml
        replicas: 1
        inputVars:
          containerImage: registry.k8s.io/pause:3.1
