---
global:
  indexerConfig:
    enabled: false
    esServers: [http://elastic-elk.apps.rsevilla.kube-burner.com]
    insecureSkipVerify: true
    defaultIndex: kube-burner
    type: elastic
  measurements:
    - name: podLatency
      thresholds:
      - conditionType: Ready
        metric: Avg
        threshold: 4s


jobs:
  - name: kubelet-density
    jobIterations: 50
    qps: 20
    burst: 20
    namespacedIterations: false
    namespace: kubelet-density
    waitWhenFinished: true
    podWait: false
    objects:

      - objectTemplate: templates/pod.yml
        replicas: 1
        inputVars:
          containerImage: registry.k8s.io/pause:3.1
