---
global:
  gc: true
  gcTimeout: 12s
  measurements:
   - name: podLatency
metricsEndpoints:
  - indexer:
      type: local
jobs:
  - name: kubelet-density
    jobIterations: 10
    qps: 10
    burst: 10
    preLoadImages: false
    namespacedIterations: true
    namespace: kubelet-density
    waitWhenFinished: true
    podWait: false
    objects:

      - objectTemplate: templates/pod.yml
        replicas: 1
        inputVars:
          containerImage: registry.k8s.io/pause:3.1
