---
global:
  gc: true
  measurements:
   - name: podLatency
jobs:
  - name: kubelet-density
    jobIterations: 25
    qps: 2
    burst: 2
    preLoadImages: false
    namespacedIterations: false
    namespace: kubelet-density
    waitWhenFinished: true
    podWait: false
    objects:

      - objectTemplate: templates/pod.yml
        replicas: 1
        inputVars:
          containerImage: registry.k8s.io/pause:3.1
