kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-{{.Replica}}-{{.Iteration}}
spec:
  podSelector:
    matchLabels:
      name: webserver-{{.Replica}}-{{.Iteration}}
  ingress:
  - ports:
    - protocol: TCP
      port: 8080
