apiVersion: v1
kind: Service
metadata:
  name: service-{{ .Iteration }}-{{ .Replica }}
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: pod-served-{{ .Iteration }}
