---
apiVersion: v1
kind: Pod
metadata:
  name: pod-served-{{ .Replica }}
  labels:
    app: pod-served-{{ .Replica }}
    ns: served-ns-{{ .Replica }}
spec:
  containers:
  - name: perfapp-1
    image: quay.io/openshift-scale/nginx
    imagePullPolicy: IfNotPresent
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      periodSeconds: 30
      failureThreshold: 1
      timeoutSeconds: 15
      initialDelaySeconds: 5       
    ports:
    - containerPort: 8080        
  - args:
    - sleep
    - infinity
    name: app
    image: quay.io/centos/centos
    imagePullPolicy: IfNotPresent
    {{ if contains .probe "true" }}
    readinessProbe:
      exec:
        command:
        - ping
        - -c1
        - 172.18.0.10
    {{ end }}
      #  nodeSelector:
      #     kubernetes.io/hostname: worker{{if eq .Iteration 81}}{{printf "%03d" (add .Iteration 2)}}{{else if eq .Iteration 82}}{{printf "%03d" (add .Iteration 1)}}{{else if eq .Iteration 98}}{{printf "%03d" (add .Iteration 2)}}{{else if eq .Iteration 110}}{{printf "%03d" (add .Iteration 2)}}{{else}}{{printf "%03d" (add .Iteration 3)}}{{end}}-r640   
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/worker-spk
            operator: DoesNotExist
