name: Containers 

on:
  push:
    branches:
      - master
    tags:
      - "*" # triggers only if push new tag version

jobs:
  containers:
    name: Build container images
    runs-on: ubuntu-latest
    steps:

      - name: Install dependencies required for multi-arch builds
        run: sudo apt-get update && sudo apt-get install qemu-user-static podman fuse-overlayfs

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Login in quay
        run: podman login quay.io -u ${QUAY_USER} -p ${QUAY_TOKEN}
        env:
          QUAY_USER: ${{ secrets.QUAY_USER }}
          QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}

      - name: Build & push container images
        run: make manifest
