name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 12 * * *"

jobs:
  stale:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v8
      with:
        stale-issue-message: 'This issue has become stale and will be closed automatically within 7 days.'
        stale-pr-message: 'This pull request has become stale and will be closed automatically within 7 days.'
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        days-before-stale: 90 
        days-before-close: 7
